### ISSUE TITLE
kafka to hbase

### ISSUE THREAD

**Issue by nphouse2008** [wushujames/kafka-mysql-connector#1]
do you have any sample code on reading this kafka event of mysql and write into hbase or hdfs?

**Comment by ewencp** [comment]
@nphouse2008 The best way to accomplish that would be to combine this connector with the [HDFS Kafka Connector](https://github.com/confluentinc/kafka-connect-hdfs). If you run in the same Kafka Connect cluster, you should be able to just configure both to work with the same topic and everything should just work since the Kafka Connect cluster will use the same serialization format to write the data in the MySQL connector and to read it in the HDFS connector.

**Comment by wushujames** [comment]
Thanks for answering @ewencp!

@nphouse2008, Kafka Connect plugins are all intended to work together. They read and write to Kafka in a standard wire format, and so you can just pick and choose input plugins and output plugins and they should be able to seamless pass data to one other (via Kafka).

So this kafka-mysql-connector reads from MySQL and writes to Kafka. And then the HDFS connector that @ewencp mentioned will take the data from Kafka and write it to HDFS.

This repo is still a work-in-progress, and so I don't think you'll yet be able to use it with the HDFS Connector. In particular, this repo still needs to be updated to use the upcoming 0.9.0 API's. It is still using a version of the API from Kafka trunk a little while ago. But stay tuned for an update in the upcoming weeks, and then hopefully you'll be able to use the two connectors together.

**Comment by wanghaisheng** [comment]
how to use your  kafka-mysql-connector to read events from kafka to recreate the orginial mysql  database?

**Comment by wushujames** [comment]
@wanghaisheng Ideally, someone would write a MySQL Sink Connector. The dataflow would then be MySQL -> kafka-mysql-connector -> Kafka -> mysql-sink-connector -> MySQL.

But there isn't a MySQL Sink Connector yet.

kafka-mysql-connector can be configured to write JSON to Kafka. You might be able to read the JSON and figure out which lines to insert into MySQL.

I need to get kafka-mysql-connector updated to 0.9.0, so that other people can start playing with it, but progress is unfortunately a little slow. I hope to find more time in January.

**Comment by wanghaisheng** [comment]
another question here,do you know aesop https://github.com/Flipkart/aesop, i have not read your code yet,what is the main difference between these two ?

**Comment by wushujames** [comment]
Yeah, I've heard about Aesop. Aesop is built on top of Databus. Databus was a precursor to Kafka. Databus has its own log storage mechanism, and has ways for consumers to initialize full historical datasets as well as receive streaming updates. Databus also primarily works with Oracle, although it has a proof-of-concept adapter to listen to MySQL.

kafka-mysql-connector does not have its own log storage mechanism. It relies on Kafka for its log storage mechanism. kafka-mysql-connector provides a way for consumers to receive streaming updates, but does not yet have a way for consumers to receive full historical datasets.

**Comment by Ronniexie** [comment]
Do you know how to start kafka-connect-mongodb?
This is demo https://github.com/DataReply/kafka-connect-mongodb.
Should I  start Schema Registry before running the kafka-connect-mongodb?

**Comment by ewencp** [comment]
@Ronniexie That seems like a question more relevant for the https://github.com/DataReply/kafka-connect-mongodb repo instead of this one.

To start any connector, you make sure the connector jars are on the classpath and either submit a connector configuration on the command line (via properties file) or to the REST API (via http://docs.confluent.io/2.0.1/connect/userguide.html#post--connectors).

The use of Schema Registry is independent of any specific connector -- serialization in Connect is separate from connectors so you can mix and match connectors and data formats. If you are using Confluent's `AvroConverter`, then yes, you should make sure the Schema Registry is running before starting the connector.

**Comment by Ronniexie** [comment]
Thank you!
I put the connector jars of demo(https://github.com/DataReply/kafka-connect-mongodb)  to  kafka lib and alter connect-console-source.properties.
Running zookeeper,kafka.
and Start connector(bin/connect-standalone.sh config/connect-standalone.properties config/connect-console-source.properties).
but the date of mongodb not pull to Kafka. and don't find the topic.

**Comment by Ronniexie** [comment]
Thank you!@ewencp
I put the connector jars of demo(https://github.com/DataReply/kafka-connect-mongodb) to kafka lib and alter connect-console-source.properties.
Running zookeeper,kafka.
and Start connector(bin/connect-standalone.sh config/connect-standalone.properties config/connect-console-source.properties).
but the date of mongodb not pull to Kafka. and don't find the topic.

**Comment by ewencp** [comment]
@Ronniexie I'd suggest including some logs (it'll be difficult to tell what's going on without them) and post this either to the kafka-connect-mongodb repository (if it appears to be specific to the connector), or [Confluent's community mailing list](https://groups.google.com/forum/#!forum/confluent-platform). Your question isn't really related to this repository or bug at all.

**Comment by Ronniexie** [comment]
@ewencp Do you know the connector of demo(https://github.com/DataReply/kafka-connect-mongodb) use AvroConverter or JsonConverter?

**Comment by wushujames** [comment]
Closing this issue. For questions related to other connectors, please go to the repository for the connector.

You can find a list of other connectors at http://www.confluent.io/product/connectors
